name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *" # 每天运行一次
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Generate snake game
        uses: Platane/snk@v2
        with:
          github_user_name: Canmi21

      - name: Commit and push the generated snake game
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Add generated snake game'
          file_pattern: snake.svg
          branch: main
